version: "3.0"

services:
  db:
    image: postgres:9.6
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: api
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:5.0.3
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./redisdata:/data
