version: "3.7"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: api
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "6969:5432"

  # api:
  #   build: "."
  #   depends_on:
  #     - db
  #   ports:
  #     - "8000:8000"
