version: "3.7"
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: api
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "6969:5432"

#   api:
#     build: "."
#     depends_on:
#       - db
#     networks:
#       - postgres
#     ports:
#       - "4000:4000"

#     restart: unless-stopped
